from aiogram.dispatcher.filters.state import State, StatesGroup

class HomeDacha(StatesGroup):
    region = State()
    umumiyMaydon = State()
    xonalar = State()
    qavatlik = State()
    remont = State()
    jihozlar = State()
    gaz = State()
    svet = State()
    suv = State()
    kanalizatsiya = State()
    qoshimchaMalumot = State()
    valyuta = State()
    narxi = State()
    manzil = State()
    moljal = State()
    telNumberOne = State()
    telNumberTwo = State()
    images = State()
    check = State()
